/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingIndexRouteImport } from './routes/setting/index'
import { Route as SettingPostIdRouteImport } from './routes/setting/$postId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingIndexRoute = SettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingPostIdRoute = SettingPostIdRouteImport.update({
  id: '/setting/$postId',
  path: '/setting/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setting/$postId': typeof SettingPostIdRoute
  '/setting': typeof SettingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setting/$postId': typeof SettingPostIdRoute
  '/setting': typeof SettingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/setting/$postId': typeof SettingPostIdRoute
  '/setting/': typeof SettingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/setting/$postId' | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/setting/$postId' | '/setting'
  id: '__root__' | '/' | '/about' | '/setting/$postId' | '/setting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SettingPostIdRoute: typeof SettingPostIdRoute
  SettingIndexRoute: typeof SettingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting/$postId': {
      id: '/setting/$postId'
      path: '/setting/$postId'
      fullPath: '/setting/$postId'
      preLoaderRoute: typeof SettingPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting/': {
      id: '/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/about' {
  const createFileRoute: CreateFileRoute<
    '/about',
    FileRoutesByPath['/about']['parentRoute'],
    FileRoutesByPath['/about']['id'],
    FileRoutesByPath['/about']['path'],
    FileRoutesByPath['/about']['fullPath']
  >
}
declare module './routes/setting/$postId' {
  const createFileRoute: CreateFileRoute<
    '/setting/$postId',
    FileRoutesByPath['/setting/$postId']['parentRoute'],
    FileRoutesByPath['/setting/$postId']['id'],
    FileRoutesByPath['/setting/$postId']['path'],
    FileRoutesByPath['/setting/$postId']['fullPath']
  >
}
declare module './routes/setting/index' {
  const createFileRoute: CreateFileRoute<
    '/setting/',
    FileRoutesByPath['/setting/']['parentRoute'],
    FileRoutesByPath['/setting/']['id'],
    FileRoutesByPath['/setting/']['path'],
    FileRoutesByPath['/setting/']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SettingPostIdRoute: SettingPostIdRoute,
  SettingIndexRoute: SettingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
